const fs = require('fs');
const path = require('path');

const listTranslations = {
    en: {
        "title": "My Listings",
        "sub": "Manage your crop auctions",
        "create": "Create Auction",
        "active": "Active\nAuctions",
        "ending": "Ending\nSoon",
        "bids_today": "Bids\nToday",
        "won_sold": "Auctions\nWon/Sold",
        "filter_all": "All",
        "filter_active": "Active",
        "filter_ended": "Ended",
        "filter_sold": "Sold",
        "no_listings": "You have no listings yet",
        "warn": "Ending Soon (Less than 1 hr)",
        "badge_live": "LIVE",
        "badge_sold": "SOLD",
        "badge_end": "ENDED",
        "base_price": "Base Price",
        "time_left": "Time Left",
        "highest_bid": "Highest Bid",
        "total_bids": "Total Bids",
        "winning_bid": "Winning Bid",
        "winner": "Winner",
        "monitor_auction": "Monitor Auction",
        "end_auction_btn": "End Auction",
        "message_buyer": "Message Buyer",
        "view_result": "View Result",
        "error_load": "Could not load listings",
        "auction_ended": "Auction ended!",
        "failed_end": "Failed to end auction.",
        "confirm_end": "Are you sure you want to end the auction for {{crop}}?",
        "end_auction_q": "End Auction?",
        "chat_error": "Could not start chat."
    },
    ta: {
        "title": "எனது பட்டியல்கள்",
        "sub": "உங்கள் பயிர் ஏலங்களை நிர்வகிக்கவும்",
        "create": "ஏலத்தை உருவாக்கு",
        "active": "செயலிலுள்ள\nஏலங்கள்",
        "ending": "விரைவில்\nமுடியும்",
        "bids_today": "இன்றைய\nஏலங்கள்",
        "won_sold": "ஏலங்கள்\nவென்றது/விற்கப்பட்டது",
        "filter_all": "அனைத்தும்",
        "filter_active": "செயலில்",
        "filter_ended": "முடிந்தது",
        "filter_sold": "விற்கப்பட்டது",
        "no_listings": "உங்களிடம் இன்னும் எந்தப் பட்டியலும் இல்லை",
        "warn": "விரைவில் முடியும் (1 மணிநேரத்திற்கு குறைவானது)",
        "badge_live": "நேரலை",
        "badge_sold": "விற்கப்பட்டது",
        "badge_end": "முடிந்தது",
        "base_price": "அடிப்படை விலை",
        "time_left": "மீதமுள்ள நேரம்",
        "highest_bid": "அதிகபட்ச ஏலம்",
        "total_bids": "மொத்த ஏலங்கள்",
        "winning_bid": "வென்ற ஏலம்",
        "winner": "வெற்றியாளர்",
        "monitor_auction": "ஏலத்தை கண்காணிக்கவும்",
        "end_auction_btn": "ஏலத்தை முடிக்கவும்",
        "message_buyer": "வாங்குபவருக்கு செய்தியனுப்பு",
        "view_result": "முடிவைப் பார்க்கவும்",
        "error_load": "பட்டியல்களை ஏற்ற முடியவில்லை",
        "auction_ended": "ஏலம் முடிந்தது!",
        "failed_end": "ஏலத்தை முடிப்பதில் தோல்வி.",
        "confirm_end": "{{crop}} ஏலத்தை முடிக்க விரும்புகிறீர்களா?",
        "end_auction_q": "ஏலத்தை முடிக்கவா?",
        "chat_error": "அரட்டையைத் தொடங்க முடியவில்லை."
    },
    hi: {
        "title": "मेरी लिस्टिंग",
        "sub": "अपनी फसल नीलामी प्रबंधित करें",
        "create": "नीलामी बनाएँ",
        "active": "सक्रिय\nनीलामियाँ",
        "ending": "जल्द\nसमाप्त",
        "bids_today": "आज की\nबोलियां",
        "won_sold": "नीलामी\nजीती/बिकी",
        "filter_all": "सभी",
        "filter_active": "सक्रिय",
        "filter_ended": "समाप्त",
        "filter_sold": "बिका हुआ",
        "no_listings": "आपके पास अभी तक कोई लिस्टिंग नहीं है",
        "warn": "जल्द समाप्त (1 घंटे से कम)",
        "badge_live": "लाइव",
        "badge_sold": "बिका हुआ",
        "badge_end": "समाप्त",
        "base_price": "मूल मूल्य",
        "time_left": "बचा हुआ समय",
        "highest_bid": "उच्चतम बोली",
        "total_bids": "कुल बोलियां",
        "winning_bid": "जीतने वाली बोली",
        "winner": "विजेता",
        "monitor_auction": "नीलामी की निगरानी करें",
        "end_auction_btn": "नीलामी समाप्त करें",
        "message_buyer": "खरीदार को संदेश भेजें",
        "view_result": "परिणाम देखें",
        "error_load": "लिस्टिंग लोड नहीं हो सकी",
        "auction_ended": "नीलामी समाप्त हो गई!",
        "failed_end": "नीलामी समाप्त करने में विफल।",
        "confirm_end": "क्या आप वाकई {{crop}} की नीलामी समाप्त करना चाहते हैं?",
        "end_auction_q": "नीलामी समाप्त करें?",
        "chat_error": "चैट शुरू नहीं हो सकी।"
    },
    te: {
        "title": "నా జాబితాలు",
        "sub": "మీ పంట వేలంపాటలను నిర్వహించండి",
        "create": "వేలంపాట సృష్టించండి",
        "active": "చురుకైన\nవేలంపాటలు",
        "ending": "త్వరలో\nముగుస్తుంది",
        "bids_today": "నేటి\nబిడ్లు",
        "won_sold": "వేలంపాటలు\nగెలిచాయి/అమ్మబడ్డాయి",
        "filter_all": "అన్ని",
        "filter_active": "చురుకైనవి",
        "filter_ended": "ముగిసినవి",
        "filter_sold": "అమ్మబడ్డవి",
        "no_listings": "మీకు ఇంకా జాబితాలు లేవు",
        "warn": "త్వరలో ముగుస్తుంది (1 గంట కంటే తక్కువ)",
        "badge_live": "లైవ్",
        "badge_sold": "అమ్మబడింది",
        "badge_end": "ముగిసింది",
        "base_price": "ప్రారంభ ధర",
        "time_left": "మిగిలిన సమయం",
        "highest_bid": "అత్యధిక బిడ్",
        "total_bids": "మొత్తం బిడ్లు",
        "winning_bid": "గెలిచిన బిడ్",
        "winner": "విజేత",
        "monitor_auction": "వేలంపాటను పర్యవేక్షించండి",
        "end_auction_btn": "వేలంపాటను ముగించండి",
        "message_buyer": "కొనుగోలుదారుకు సందేశం పంపండి",
        "view_result": "ఫలితాన్ని వీక్షించండి",
        "error_load": "జాబితాలను లోడ్ చేయలేకపోయాము",
        "auction_ended": "వేలంపాట ముగిసింది!",
        "failed_end": "వేలంపాటను ముగించడంలో విఫలమైంది.",
        "confirm_end": "{{crop}} కోసం వేలంపాటను ముగించాలనుకుంటున్నారా?",
        "end_auction_q": "వేలంపాటను ముగించాలా?",
        "chat_error": "చాట్‌ను ప్రారంభించలేకపోయాము."
    },
    ml: {
        "title": "എന്റെ ലിസ്റ്റിംഗുകൾ",
        "sub": "നിങ്ങളുടെ വിള ലേലങ്ങൾ കൈകാര്യം ചെയ്യുക",
        "create": "ലേലം സൃഷ്ടിക്കുക",
        "active": "സജീവമായ\nലേലങ്ങൾ",
        "ending": "ഉടൻ\nഅവസാനിക്കുന്നു",
        "bids_today": "ഇന്നത്തെ\nബിഡുകൾ",
        "won_sold": "ലേലങ്ങൾ\nവിജയിച്ചു/വിറ്റു",
        "filter_all": "എല്ലാം",
        "filter_active": "സജീവമായവ",
        "filter_ended": "അവസാനിച്ചവ",
        "filter_sold": "വിറ്റവ",
        "no_listings": "നിങ്ങൾക്ക് ഇതുവരെ ലിസ്റ്റിംഗുകളൊന്നുമില്ല",
        "warn": "ഉടൻ അവസാനിക്കുന്നു (1 മണിക്കൂറിൽ താഴെ)",
        "badge_live": "തത്സമയം",
        "badge_sold": "വിറ്റു",
        "badge_end": "അവസാനിച്ചു",
        "base_price": "അടിസ്ഥാന വില",
        "time_left": "ശേഷിക്കുന്ന സമയം",
        "highest_bid": "ഏറ്റവും ഉയർന്ന ബിഡ്",
        "total_bids": "മൊത്തം ബിഡുകൾ",
        "winning_bid": "വിജയിച്ച ബിഡ്",
        "winner": "വിജയി",
        "monitor_auction": "ലേലം നിരീക്ഷിക്കുക",
        "end_auction_btn": "ലേലം അവസാനിപ്പിക്കുക",
        "message_buyer": "വാങ്ങുന്നയാൾക്ക് സന്ദേശം അയയ്ക്കുക",
        "view_result": "ഫലം കാണുക",
        "error_load": "ലിസ്റ്റിംഗുകൾ ലോഡുചെയ്യാനായില്ല",
        "auction_ended": "ലേലം അവസാനിച്ചു!",
        "failed_end": "ലേലം അവസാനിപ്പിക്കുന്നതിൽ പരാജയപ്പെട്ടു.",
        "confirm_end": "{{crop}} ലേലം അവസാനിപ്പിക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?",
        "end_auction_q": "ലേലം അവസാനിപ്പിക്കണോ?",
        "chat_error": "ചാറ്റ് ആരംഭിക്കാനായില്ല."
    }
};

const notificationsTranslations = {
    en: {
        "title": "Notifications",
        "mark_read": "Mark all read",
        "empty": "No notifications yet"
    },
    hi: {
        "title": "सूचनाएं",
        "mark_read": "सभी को पढ़ लिया चिह्नित करें",
        "empty": "अभी तक कोई सूचना नहीं"
    },
    ta: {
        "title": "அறிவிப்புகள்",
        "mark_read": "அனைத்தையும் படித்ததாக குறிக்கவும்",
        "empty": "அறிவிப்புகள் ஏதுமில்லை"
    },
    te: {
        "title": "నోటిఫికేషన్‌లు",
        "mark_read": "అన్నిటినీ చదివినట్లుగా గుర్తించు",
        "empty": "ఇంకా నోటిఫికేషన్‌లు లేవు"
    },
    ml: {
        "title": "അറിയിപ്പുകൾ",
        "mark_read": "എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക",
        "empty": "അറിയിപ്പുകളൊന്നുമില്ല"
    }
};

const createAuctionTranslations = {
    en: {
        "title": "Create Live Auction",
        "section_a": "A. CROP DETAILS",
        "crop_name": "Crop Name",
        "crop_ph": "e.g. Wheat, Basmati Rice",
        "variety": "Variety (Optional)",
        "variety_ph": "e.g. Sharbati, 1121",
        "quantity": "Quantity",
        "unit": "Unit",
        "quality": "Quality Grade",
        "harvest_date": "Harvest Date",
        "upload_photos": "Upload Photos (Optional)",
        "section_b": "B. PRICING STRATEGY",
        "start_price": "Starting Price",
        "per": "per",
        "reserve_price": "Reserve Price (Optional)",
        "reserve_help": "Minimum acceptable price. Auction only completes if highest bid ≥ reserve price.",
        "min_increment": "Minimum Bid Increment",
        "min_help": "Prevents ₹1 increments.",
        "section_c": "C. AUCTION TIMING",
        "duration": "Duration",
        "duration_warn": "Warning: Short auctions (< 1 hour) often attract fewer buyers.",
        "section_d": "D. LOGISTICS",
        "pickup": "Pickup Location (Village/District)",
        "delivery_type": "Delivery Type",
        "start_btn": "Start Auction",
        "missing_fields": "Please fill in all required fields.",
        "auth_err": "You must be logged in to create an auction.",
        "success": "Your crop is now live for buyers to bid!",
        "err": "Could not create auction. Please try again."
    },
    hi: {
        "title": "लाइव नीलामी बनाएँ",
        "section_a": "A. फसल का विवरण",
        "crop_name": "फसल का नाम",
        "crop_ph": "उदा. गेहूं, बासमती चावल",
        "variety": "किस्म (वैकल्पिक)",
        "variety_ph": "उदा. शरबती, 1121",
        "quantity": "मात्रा",
        "unit": "इकाई",
        "quality": "गुणवत्ता ग्रेड",
        "harvest_date": "कटाई की तारीख",
        "upload_photos": "तस्वीरें अपलोड करें (वैकल्पिक)",
        "section_b": "B. मूल्य निर्धारण रणनीति",
        "start_price": "शुरुआती कीमत",
        "per": "प्रति",
        "reserve_price": "आरक्षित मूल्य (वैकल्पिक)",
        "reserve_help": "न्यूनतम स्वीकार्य कीमत। उच्चतम बोली आरक्षित मूल्य के बराबर या उससे अधिक होने पर ही नीलामी पूरी होती है।",
        "min_increment": "न्यूनतम बोली वृद्धि",
        "min_help": "₹1 की वृद्धि रोकता है।",
        "section_c": "C. नीलामी का समय",
        "duration": "अवधि",
        "duration_warn": "चेतावनी: छोटी नीलामियां (< 1 घंटे) अक्सर कम खरीदारों को आकर्षित करती हैं।",
        "section_d": "D. रसद",
        "pickup": "पिकअप स्थान (गांव/जिला)",
        "delivery_type": "डिलीवरी का प्रकार",
        "start_btn": "नीलामी शुरू करें",
        "missing_fields": "कृपया सभी आवश्यक फ़ील्ड भरें।",
        "auth_err": "नीलामी बनाने के लिए आपको लॉग इन होना चाहिए।",
        "success": "आपकी फसल अब खरीदारों के लिए बोली लगाने के लिए लाइव है!",
        "err": "नीलामी नहीं बना सका। कृपया पुनः प्रयास करें।"
    },
    ta: {
        "title": "நேரலை ஏலத்தை உருவாக்கு",
        "section_a": "A. பயிர் விவரங்கள்",
        "crop_name": "பயிரின் பெயர்",
        "crop_ph": "எ.கா. கோதுமை, பாசுமதி",
        "variety": "ரகம் (பொருந்தினால்)",
        "variety_ph": "எ.கா. சம்பா, 1121",
        "quantity": "அளவு",
        "unit": "அலகு",
        "quality": "தர நிலை (Grade)",
        "harvest_date": "அறுவடை தேதி",
        "upload_photos": "புகைப்படங்களை பதிவேற்று (விருப்பமானால்)",
        "section_b": "B. விலை நிர்ணயம்",
        "start_price": "ஆரம்ப விலை",
        "per": "ஒரு",
        "reserve_price": "குறைந்தபட்ச விலை (விருப்பமானால்)",
        "reserve_help": "இந்த அளவை விட ஏலம் அதிகமாக இருந்தால் மட்டுமே இறுதி செய்யப்படும்.",
        "min_increment": "குறைந்தபட்ச ஏல உயர்வு",
        "min_help": "₹1 உயர்வை தடுக்கிறது.",
        "section_c": "C. ஏல நேரம்",
        "duration": "கால அளவு",
        "duration_warn": "எச்சரிக்கை: குறுகிய ஏலங்கள் (< 1 மணிநேரம்) குறைந்த வாங்குபவர்களையே ஈர்க்கின்றன.",
        "section_d": "D. போக்குவரத்து",
        "pickup": "எடுக்கும் இடம் (கிராமம்/மாவட்டம்)",
        "delivery_type": "பிக்-அப் முறை",
        "start_btn": "ஏலத்தைத் தொடங்கு",
        "missing_fields": "அனைத்து கட்டாய புலங்களையும் நிரப்பவும்.",
        "auth_err": "ஏலத்தை அமைக்க நீங்கள் உள்நுழைந்திருக்க வேண்டும்.",
        "success": "உங்கள் பயிர் இப்போது ஏலத்திற்கு தயாராக உள்ளது!",
        "err": "ஏலத்தை உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்."
    },
    te: {
        "title": "లైవ్ వేలంపాట సృష్టించండి",
        "section_a": "A. పంట వివరాలు",
        "crop_name": "పంట పేరు",
        "crop_ph": "ఉదా. గోధుమ, బాస్మతి బియ్యం",
        "variety": "రకం (ఐచ్ఛికం)",
        "variety_ph": "ఉదా. శర్బతి, 1121",
        "quantity": "పరిమాణం",
        "unit": "యూనిట్",
        "quality": "నాణ్యత గ్రేడ్",
        "harvest_date": "కోత తేదీ",
        "upload_photos": "ఫోటోలను అప్‌లోడ్ చేయండి (ఐచ్ఛికం)",
        "section_b": "B. ధర విధానం",
        "start_price": "ప్రారంభ ధర",
        "per": "ప్రతి",
        "reserve_price": "కనీస ధర (ఐచ్ఛికం)",
        "reserve_help": "అంగీకరించదగిన కనీస ధర. అత్యధిక బిడ్ ≥ రిజర్వ్ ధర ఉంటే మాత్రమే వేలం ముగుస్తుంది.",
        "min_increment": "కనీస బిడ్ పెంపు",
        "min_help": "₹1 పెంపును నివారిస్తుంది.",
        "section_c": "C. వేలం టైమింగ్",
        "duration": "వ్యవధి",
        "duration_warn": "హెచ్చరిక: చిన్న వేలంపాటలు (< 1 గంట) తక్కువ కొనుగోలుదారులను ఆకర్షిస్తాయి.",
        "section_d": "D. రవాణా",
        "pickup": "పికప్ స్థానం (గ్రామం/జిల్లా)",
        "delivery_type": "డెలివరీ రకం",
        "start_btn": "వేలంపాట ప్రారంభించండి",
        "missing_fields": "దయచేసి అన్ని అవసరమైన ఫీల్డ్‌లను పూరించండి.",
        "auth_err": "వేలం సృష్టించడానికి మీరు లాగిన్ అయి ఉండాలి.",
        "success": "మీ పంట ఇప్పుడు కొనుగోలుదారుల కోసం లైవ్‌లో ఉంది!",
        "err": "వేలం సృష్టించలేకపోయాము. దయచేసి మళ్లీ ప్రయత్నించండి."
    },
    ml: {
        "title": "തത്സമയ ലേലം സൃഷ്ടിക്കുക",
        "section_a": "A. വിളയുടെ വിശദാംശങ്ങൾ",
        "crop_name": "വിളയുടെ പേര്",
        "crop_ph": "ഉദാ. ഗോതമ്പ്, ബസുമതി അരി",
        "variety": "ഇനം (ഓപ്ഷണൽ)",
        "variety_ph": "ഉദാ. ശർബതി, 1121",
        "quantity": "അളവ്",
        "unit": "യൂണിറ്റ്",
        "quality": "ഗുണനിലവാര ഗ്രേഡ്",
        "harvest_date": "വിളവെടുപ്പ് തീയതി",
        "upload_photos": "ഫോട്ടോകൾ അപ്‌ലോഡ് ചെയ്യുക (ഓപ്ഷണൽ)",
        "section_b": "B. വില നിർണ്ണയ തന്ത്രം",
        "start_price": "പ്രാരംഭ വില",
        "per": "ഒരു",
        "reserve_price": "റിസർവ് വില (ഓപ്ഷണൽ)",
        "reserve_help": "സ്വീകാര്യമായ ഏറ്റവും കുറഞ്ഞ വില. ഏറ്റവും ഉയർന്ന ബിഡ് റിസർവ് വിലയ്ക്ക് സമമോ കൂടുതലോ ആണെങ്കിൽ മാത്രമേ ലേലം പൂർത്തിയാകൂ.",
        "min_increment": "കുറഞ്ഞ വർദ്ധനവ്",
        "min_help": "₹1 വർദ്ധനവ് തടയുന്നു.",
        "section_c": "C. ലേല സമയം",
        "duration": "ദൈർഘ്യം",
        "duration_warn": "മുന്നറിയിപ്പ്: കുറഞ്ഞ സമയമുള്ള ലേലങ്ങൾ (< 1 മണിക്കൂർ) സാധാരണയായി കുറഞ്ഞ ആളുകളെ മാത്രമേ ആകർഷിക്കാറുള്ളൂ.",
        "section_d": "D. ഗതാഗതം",
        "pickup": "പിക്കപ്പ് സ്ഥലം (ഗ്രാമം/ജില്ല)",
        "delivery_type": "ഡെലിവറി തരം",
        "start_btn": "ലേലം ആരംഭിക്കുക",
        "missing_fields": "എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക.",
        "auth_err": "ലേലം സൃഷ്ടിക്കാൻ ലോഗിൻ ചെയ്യണം.",
        "success": "നിങ്ങളുടെ വിള ഇപ്പോൾ ലേലത്തിന് തയ്യാറാണ്!",
        "err": "ലേലം സൃഷ്ടിക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക."
    }
};

const i18nDir = path.join(__dirname, 'i18n');

['en', 'hi', 'ta', 'te', 'ml'].forEach(lang => {
    const filePath = path.join(i18nDir, `${lang}.json`);
    if (!fs.existsSync(filePath)) return;

    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

    data.list = Object.assign({}, data.list || {}, listTranslations[lang]);
    data.notifications = Object.assign({}, data.notifications || {}, notificationsTranslations[lang]);
    data.create_auction = Object.assign({}, data.create_auction || {}, createAuctionTranslations[lang]);

    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
});

console.log('Translations updated successfully');
